require 'yaml'

class Db < Thor

  desc 'get APP_NAME', 'Pull down the Heroku database for a specific Heroku app'
  method_option :verbose, :aliases => "-v", :desc => "Be verbose"
  def get(app)
    database_config = YAML.load(File.open("./config/database.yml"))
    database_name = database_config['development']['database']

    say "Unable to extract database config from config/database.yml" and return false unless database_name

    puts "Localising database from #{app} to local database #{database_name}"
    `/usr/local/bin/heroku pgbackups:capture --expire -a #{app}`
    `curl -o tmp/latest.dump \`/usr/local/bin/heroku pgbackups:url -a #{app}\``
    `pg_restore --verbose --clean --no-acl --no-owner -d #{database_name} tmp/latest.dump`
    `bundle exec rake ts:rebuild`
  end

end